[DEFAULT]
test_path=/opt/stack/tempest/dell_tempest_plugin/.venv/lib/python3.12/site-packages/tempest/test_discover
top_dir=/opt/stack/tempest/dell_tempest_plugin/.venv/lib/python3.12/site-packages/tempest
group_regex=([^\.]*\.)*
